# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_auto_20160620_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='gid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
